### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by mp1pro** [mmirus/bwa-u3-jammming-prj#1]
The project is missing a package.json file. Hence other coders will not be able to recreate/download and run the project easily.

**Comment by mmirus** [comment]
@mp1pro it had it, but the uploader from the project page wouldn't work when I selected all of the files. I must have selected too few--let me add the others back to the repo.

**Comment by mmirus** [comment]
@mp1pro okay, I've comitted the missing files. Everything should be there now except the node_modules folder.
